create database hidrantes;

CREATE TABLE HIDRANTE(
	ID VARCHAR(30) NOT NULL,
	CAUDAL FLOAT NOT NULL,
	NUMERO_SALIDAS INT NOT NULL,
	TAMANO_SALIDAS VARCHAR(30) NOT NULL,
	ESTADO VARCHAR(30) NOT NULL,
    LONGITUD FLOAT NOT NULL,
	LATITUD FLOAT NOT NULL,
	CONSTRAINT PKHIDRANTE PRIMARY KEY (ID)
);

CREATE TABLE USUARIO(
	ID VARCHAR(30) NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	CONTRASENA VARCHAR(30) NOT NULL,
	DEPARTAMENTO VARCHAR(30) NOT NULL,
	CONSTRAINT PKBOMBERO PRIMARY KEY (ID)
);

CREATE TABLE INSPECCION_OCULAR(
	ID VARCHAR(30) NOT NULL,
	USUARIO VARCHAR(30) NOT NULL,
	FECHA DATE NOT NULL,
	CONSTRAINT PKINSPECCION_OCULAR PRIMARY KEY (ID),
	CONSTRAINT FKINSPECCION_OCULAR FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID)
);

CREATE TABLE INSPECCION_HIDRANTE(
	INSPECCION_OCULAR VARCHAR(30) NOT NULL,
	HIDRANTE VARCHAR(30) NOT NULL,
	CONSTRAINT FK1INSPECCION_HIDRANTE FOREIGN KEY (INSPECCION_OCULAR) REFERENCES INSPECCION_OCULAR(ID),
	CONSTRAINT FK2INSPECCION_HIDRANTE FOREIGN KEY (HIDRANTE) REFERENCES HIDRANTE(ID)
);

INSERT INTO USUARIO VALUES ('111','PAOLA ZUNIGA','111','BOMBEROS');
INSERT INTO USUARIO VALUES ('222','MARIO ALFARO','222','BOMBEROS');
INSERT INTO USUARIO VALUES ('333','LUIS PEREZ','333','MUNICIPALIDAD');
INSERT INTO USUARIO VALUES ('444','MELISSA HERNANDEZ','444','MUNICIPALIDAD');