create database hidrantes;

CREATE TABLE HIDRANTE(
	CODIGO INT NOT NULL,
	CAUDAL FLOAT NOT NULL,
	NUMERO_SALIDAS INT NOT NULL,
	TAMANO_SALIDAS VARCHAR(30) NOT NULL,
	ESTADO VARCHAR(30) NOT NULL,
        LONGITUD FLOAT NOT NULL,
	LATITUD FLOAT NOT NULL,
	CONSTRAINT PKHIDRANTE PRIMARY KEY (CODIGO)
);

CREATE TABLE BOMBERO(
	CODIGO INT NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	CONSTRAINT PKBOMBERO PRIMARY KEY (CODIGO)
);

CREATE TABLE INSPECCION_OCULAR(
	CODIGO INT NOT NULL,
	BOMBERO INT NOT NULL,
	FECHA DATE NOT NULL,
	CONSTRAINT PKINSPECCION_OCULAR PRIMARY KEY (CODIGO),
	CONSTRAINT FKINSPECCION_OCULAR FOREIGN KEY (BOMBERO) REFERENCES BOMBERO (CODIGO)
);

CREATE TABLE INSPECCION_HIDRANTE(
	INSPECCION_OCULAR INT NOT NULL,
	HIDRANTE INT NOT NULL,
	CONSTRAINT FK1INSPECCION_HIDRANTE FOREIGN KEY (INSPECCION_OCULAR) REFERENCES INSPECCION_OCULAR(CODIGO),
	CONSTRAINT FK2INSPECCION_HIDRANTE FOREIGN KEY (HIDRANTE) REFERENCES HIDRANTE(CODIGO)
);